
import ThemeButton from './components/ThemeButton'
import './globals.css'
import Providers from './providers'




export const metadata = {
  title: 'Daniel.jsx',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className='light' style={{colorScheme: 'light'}}>
      <body className='w-screen min-h-screen'>
                       
                <Providers>
                  {children}
                  <ThemeButton />
                </Providers>
            
        </body>
    </html> 
  )
}
