import { Inter } from 'next/font/google'
import './globals.css'



export const metadata = {
  title: 'Daniel Olagbegi',
  description: 'Generated by create next app',
}
// https://xeuxdev.vercel.app/
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='bg-[url(/bg-hero.png)] bg-gray-950  w-screen min-h-screen '>
        
                {children}
          
        </body>
    </html>
  )
}
