import './globals.css'



export const metadata = {
  title: 'Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='w-screen min-h-screen '>
              <div>
                {children}
                </div>
        </body>
    </html> 
  )
}
